#!/bin/sh
set -e
if [ "$1" = purge ]; then
  rm -rf /etc/cloudwatchd
  rm -rf /usr/local/bin/cloudwatchd
  rm -rf /var/log/cloudwatchd
  done
fi
deluser cloudwatchd
rm /usr/local/bin/cloudwatchd/cloudwatchd-worker
update-rc.d cloudwatchd remove
