#!/bin/sh
set -e
if [ "$1" = purge ]; then
    dirs="rm -rf /etc/cloudwatchd\
    rm -rf /var/log/cloudwatchd"
    for dir in "$dirs"
        do if [ -d "$dir" ]
            then rm -rf "$dir"
            fi
        done
fi

if [ $(grep cloudwatchd /etc/shadow -c) -ne 0 ]
    then deluser cloudwatchd
fi

update-rc.d cloudwatchd remove -f
