#!/bin/sh
set -e
if [ $(service cloudwatchd status | grep pid -c) -eq 1 ]
    then service cloudwatchd stop
fi

for proc in $(ps h -U cloudwatchd -o pid)
    do kill -9 $proc
    done

leftover_procs=$(ps h -U cloudwatchd -o pid)
if [ -n "$leftover_procs" ]
    then
        echo "Some processes running as cloudwatchd could not be stopped:\
        $leftover_procs"
        exit 1
fi
