#!/bin/sh
set -e
if [ "$1" = purge ]; then
    rm -rf /etc/cloudwatchd
    rm -rf /var/log/cloudwatchd
fi

if [ -n `grep $DAEMON_USER /etc/shadow` ]
    then deluser cloudwatchd
fi

chkconfig --del cloudwatchd
